#!/bin/bash

. /root/.bash_profile
set -e

aub=/aufs/system/root/httpd

# download the packages
if [ -d $aub ]; then
	rm -rf $aub;
fi
mkdir $aub
/bin/yumdownloader --archlist=x86_64 --destdir=$aub httpd
rm -f $aub/*i686*

cat <<EOF >/aufs/sysbase/tmp/httpd
set -e
# httpd doesn't install by default because of sys-set-cap on suexec failure due to aufs
# we do 1/3 of the work here
# also, use the just downloaded packages
yum install -y $(ls /root/httpd | while read line; do echo "/root/httpd/$line"; done | tr '\n' ' ') || true
RPM="\$(ls /root/httpd | while read line; do echo "/root/httpd/\$line"; done | tr '\n' ' ')"
# now mark the packages installed in the rpm DB (2/3 of work)
for i in \$RPM; do
	/bin/rpm --justdb -i \$i || true
done
EOF
sysexec bash /tmp/httpd

# now extract the packages (3/3 of work)
pushd /aufs/system >/dev/null 2>&1
for i in root/httpd/*.rpm; do
	rpm2cpio $i | cpio -idu >/dev/null 2>&1;
done

popd >/dev/null 2>&1

# cleanup
rm -rf /aufs/system/root/httpd

